//
// Created by mx on 2020/7/20.
//

#ifndef LOTTIERECODER_FFMPEG_HELLO_H
#define LOTTIERECODER_FFMPEG_HELLO_H

#endif //LOTTIERECODER_FFMPEG_HELLO_H
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ferris_medialib */

#ifndef _Included_com_ferris_medialib
#define _Included_com_ferris_medialib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ferris_medialib
 * Method:    urlprotocolinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ferris_medialib_urlprotocolinfo
        (JNIEnv *, jobject);

/*
 * Class:     com_ferris_medialib
 * Method:    avformatinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ferris_medialib_avformatinfo
        (JNIEnv *, jobject);

/*
 * Class:     com_ferris_medialib
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ferris_medialib_avcodecinfo
        (JNIEnv *, jobject);

/*
 * Class:     com_ferris_medialib
 * Method:    avfilterinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ferris_medialib_avfilterinfo
        (JNIEnv *, jobject);

/*
 * Class:     com_ferris_medialib
 * Method:    configurationinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ferris_medialib_configurationinfo
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif